# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Custom_List_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Custom_List_Widget(object):
    def setupUi(self, Custom_List_Widget):
        Custom_List_Widget.setObjectName("Custom_List_Widget")
        Custom_List_Widget.resize(242, 131)
        self.gridLayout = QtWidgets.QGridLayout(Custom_List_Widget)
        self.gridLayout.setContentsMargins(-1, 9, -1, -1)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 4, 1, 1)
        self.label_Icon = QtWidgets.QLabel(Custom_List_Widget)
        self.label_Icon.setObjectName("label_Icon")
        self.gridLayout.addWidget(self.label_Icon, 0, 1, 5, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text_Main_Contact = QtWidgets.QLabel(Custom_List_Widget)
        self.text_Main_Contact.setObjectName("text_Main_Contact")
        self.horizontalLayout.addWidget(self.text_Main_Contact)
        self.text_Name_Change = QtWidgets.QLabel(Custom_List_Widget)
        self.text_Name_Change.setObjectName("text_Name_Change")
        self.horizontalLayout.addWidget(self.text_Name_Change)
        self.label_7 = QtWidgets.QLabel(Custom_List_Widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.text_PhoneNumber_CHANGE = QtWidgets.QLabel(Custom_List_Widget)
        self.text_PhoneNumber_CHANGE.setObjectName("text_PhoneNumber_CHANGE")
        self.horizontalLayout.addWidget(self.text_PhoneNumber_CHANGE)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.text_Due_Date = QtWidgets.QLabel(Custom_List_Widget)
        self.text_Due_Date.setObjectName("text_Due_Date")
        self.horizontalLayout_2.addWidget(self.text_Due_Date)
        self.text_Date_CHANGE = QtWidgets.QLabel(Custom_List_Widget)
        self.text_Date_CHANGE.setObjectName("text_Date_CHANGE")
        self.horizontalLayout_2.addWidget(self.text_Date_CHANGE)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.text_ProjectNumber_CHANGE = QtWidgets.QLabel(Custom_List_Widget)
        self.text_ProjectNumber_CHANGE.setObjectName("text_ProjectNumber_CHANGE")
        self.horizontalLayout_3.addWidget(self.text_ProjectNumber_CHANGE)
        self.text_dash = QtWidgets.QLabel(Custom_List_Widget)
        self.text_dash.setObjectName("text_dash")
        self.horizontalLayout_3.addWidget(self.text_dash)
        self.text_Project_Name_Change = QtWidgets.QLabel(Custom_List_Widget)
        self.text_Project_Name_Change.setObjectName("text_Project_Name_Change")
        self.horizontalLayout_3.addWidget(self.text_Project_Name_Change)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 3, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.text_nextDeliverible = QtWidgets.QLabel(Custom_List_Widget)
        self.text_nextDeliverible.setObjectName("text_nextDeliverible")
        self.horizontalLayout_6.addWidget(self.text_nextDeliverible)
        self.text_NextDeliverible_CHANGE = QtWidgets.QLabel(Custom_List_Widget)
        self.text_NextDeliverible_CHANGE.setObjectName("text_NextDeliverible_CHANGE")
        self.horizontalLayout_6.addWidget(self.text_NextDeliverible_CHANGE)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 3, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.text_Project_Folder = QtWidgets.QLabel(Custom_List_Widget)
        self.text_Project_Folder.setObjectName("text_Project_Folder")
        self.horizontalLayout_5.addWidget(self.text_Project_Folder)
        self.text_ProjectFolder_CHANGE = QtWidgets.QLabel(Custom_List_Widget)
        self.text_ProjectFolder_CHANGE.setObjectName("text_ProjectFolder_CHANGE")
        self.horizontalLayout_5.addWidget(self.text_ProjectFolder_CHANGE)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 3, 1, 1)
        self.line = QtWidgets.QFrame(Custom_List_Widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 0, 1, 5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 3, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 0, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 4, 4, 1, 1)

        self.retranslateUi(Custom_List_Widget)
        QtCore.QMetaObject.connectSlotsByName(Custom_List_Widget)

    def retranslateUi(self, Custom_List_Widget):
        _translate = QtCore.QCoreApplication.translate
        Custom_List_Widget.setWindowTitle(_translate("Custom_List_Widget", "Form"))
        self.label_Icon.setText(_translate("Custom_List_Widget", "Icon"))
        self.text_Main_Contact.setText(_translate("Custom_List_Widget", "Main Contact:  "))
        self.text_Name_Change.setText(_translate("Custom_List_Widget", "Name"))
        self.label_7.setText(_translate("Custom_List_Widget", ", "))
        self.text_PhoneNumber_CHANGE.setText(_translate("Custom_List_Widget", "Phone Number"))
        self.text_Due_Date.setText(_translate("Custom_List_Widget", "Final Due Date: "))
        self.text_Date_CHANGE.setText(_translate("Custom_List_Widget", "Date"))
        self.text_ProjectNumber_CHANGE.setText(_translate("Custom_List_Widget", "Project Number"))
        self.text_dash.setText(_translate("Custom_List_Widget", " - "))
        self.text_Project_Name_Change.setText(_translate("Custom_List_Widget", "ProjectName"))
        self.text_nextDeliverible.setText(_translate("Custom_List_Widget", "Next Deliveriable:  "))
        self.text_NextDeliverible_CHANGE.setText(_translate("Custom_List_Widget", "TextLabel"))
        self.text_Project_Folder.setText(_translate("Custom_List_Widget", "Project Folder: "))
        self.text_ProjectFolder_CHANGE.setText(_translate("Custom_List_Widget", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Custom_List_Widget = QtWidgets.QWidget()
    ui = Ui_Custom_List_Widget()
    ui.setupUi(Custom_List_Widget)
    Custom_List_Widget.show()
    sys.exit(app.exec_())

