# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Load_Input.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoadInput(object):
    def setupUi(self, LoadInput):
        LoadInput.setObjectName("LoadInput")
        LoadInput.resize(707, 695)
        self.gridLayout = QtWidgets.QGridLayout(LoadInput)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_UserInput = QtWidgets.QGroupBox(LoadInput)
        self.groupBox_UserInput.setObjectName("groupBox_UserInput")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_UserInput)
        self.verticalLayout.setObjectName("verticalLayout")
        self.GroupBoxLayOut_top_hoz = QtWidgets.QHBoxLayout()
        self.GroupBoxLayOut_top_hoz.setObjectName("GroupBoxLayOut_top_hoz")
        self.Text_Load_Name = QtWidgets.QLabel(self.groupBox_UserInput)
        self.Text_Load_Name.setObjectName("Text_Load_Name")
        self.GroupBoxLayOut_top_hoz.addWidget(self.Text_Load_Name)
        self.UserInput_Load_Name = QtWidgets.QLineEdit(self.groupBox_UserInput)
        self.UserInput_Load_Name.setObjectName("UserInput_Load_Name")
        self.GroupBoxLayOut_top_hoz.addWidget(self.UserInput_Load_Name)
        self.Text_Voltage = QtWidgets.QLabel(self.groupBox_UserInput)
        self.Text_Voltage.setObjectName("Text_Voltage")
        self.GroupBoxLayOut_top_hoz.addWidget(self.Text_Voltage)
        self.comboBox_Voltage = QtWidgets.QComboBox(self.groupBox_UserInput)
        self.comboBox_Voltage.setObjectName("comboBox_Voltage")
        self.GroupBoxLayOut_top_hoz.addWidget(self.comboBox_Voltage)
        self.verticalLayout.addLayout(self.GroupBoxLayOut_top_hoz)
        self.GroupBoxLayOut_bottom_hoz = QtWidgets.QHBoxLayout()
        self.GroupBoxLayOut_bottom_hoz.setObjectName("GroupBoxLayOut_bottom_hoz")
        self.Text_Wattage = QtWidgets.QLabel(self.groupBox_UserInput)
        self.Text_Wattage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Text_Wattage.setObjectName("Text_Wattage")
        self.GroupBoxLayOut_bottom_hoz.addWidget(self.Text_Wattage)
        self.UserInput_Wattage = QtWidgets.QLineEdit(self.groupBox_UserInput)
        self.UserInput_Wattage.setObjectName("UserInput_Wattage")
        self.GroupBoxLayOut_bottom_hoz.addWidget(self.UserInput_Wattage)
        self.Text_Power_Factor = QtWidgets.QLabel(self.groupBox_UserInput)
        self.Text_Power_Factor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Text_Power_Factor.setObjectName("Text_Power_Factor")
        self.GroupBoxLayOut_bottom_hoz.addWidget(self.Text_Power_Factor)
        self.UserInput_Power_Factor = QtWidgets.QLineEdit(self.groupBox_UserInput)
        self.UserInput_Power_Factor.setObjectName("UserInput_Power_Factor")
        self.GroupBoxLayOut_bottom_hoz.addWidget(self.UserInput_Power_Factor)
        self.Text_VA = QtWidgets.QLabel(self.groupBox_UserInput)
        self.Text_VA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Text_VA.setObjectName("Text_VA")
        self.GroupBoxLayOut_bottom_hoz.addWidget(self.Text_VA)
        self.Text_VA_RESULTS = QtWidgets.QLabel(self.groupBox_UserInput)
        self.Text_VA_RESULTS.setObjectName("Text_VA_RESULTS")
        self.GroupBoxLayOut_bottom_hoz.addWidget(self.Text_VA_RESULTS)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.GroupBoxLayOut_bottom_hoz.addItem(spacerItem)
        self.Text_Utility = QtWidgets.QLabel(self.groupBox_UserInput)
        self.Text_Utility.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Text_Utility.setObjectName("Text_Utility")
        self.GroupBoxLayOut_bottom_hoz.addWidget(self.Text_Utility)
        self.comboBox_Utility = QtWidgets.QComboBox(self.groupBox_UserInput)
        self.comboBox_Utility.setObjectName("comboBox_Utility")
        self.GroupBoxLayOut_bottom_hoz.addWidget(self.comboBox_Utility)
        self.verticalLayout.addLayout(self.GroupBoxLayOut_bottom_hoz)
        self.gridLayout.addWidget(self.groupBox_UserInput, 0, 0, 1, 1)
        self.Middle_LayOut_hoz = QtWidgets.QHBoxLayout()
        self.Middle_LayOut_hoz.setObjectName("Middle_LayOut_hoz")
        self.tableWidget = QtWidgets.QTableWidget(LoadInput)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.Middle_LayOut_hoz.addWidget(self.tableWidget)
        self.gridLayout.addLayout(self.Middle_LayOut_hoz, 2, 0, 1, 1)
        self.Top2_LayOut_hoz = QtWidgets.QHBoxLayout()
        self.Top2_LayOut_hoz.setObjectName("Top2_LayOut_hoz")
        self.Button_Add_To_Window = QtWidgets.QPushButton(LoadInput)
        self.Button_Add_To_Window.setObjectName("Button_Add_To_Window")
        self.Top2_LayOut_hoz.addWidget(self.Button_Add_To_Window)
        self.Button_Modify_Load = QtWidgets.QPushButton(LoadInput)
        self.Button_Modify_Load.setObjectName("Button_Modify_Load")
        self.Top2_LayOut_hoz.addWidget(self.Button_Modify_Load)
        self.Button_Remove_Load = QtWidgets.QPushButton(LoadInput)
        self.Button_Remove_Load.setObjectName("Button_Remove_Load")
        self.Top2_LayOut_hoz.addWidget(self.Button_Remove_Load)
        self.gridLayout.addLayout(self.Top2_LayOut_hoz, 1, 0, 1, 1)

        self.retranslateUi(LoadInput)
        QtCore.QMetaObject.connectSlotsByName(LoadInput)
        LoadInput.setTabOrder(self.UserInput_Load_Name, self.UserInput_Wattage)
        LoadInput.setTabOrder(self.UserInput_Wattage, self.UserInput_Power_Factor)
        LoadInput.setTabOrder(self.UserInput_Power_Factor, self.tableWidget)
        LoadInput.setTabOrder(self.tableWidget, self.Button_Add_To_Window)
        LoadInput.setTabOrder(self.Button_Add_To_Window, self.Button_Modify_Load)
        LoadInput.setTabOrder(self.Button_Modify_Load, self.Button_Remove_Load)

    def retranslateUi(self, LoadInput):
        _translate = QtCore.QCoreApplication.translate
        LoadInput.setWindowTitle(_translate("LoadInput", "Form"))
        self.groupBox_UserInput.setTitle(_translate("LoadInput", "Load Input"))
        self.Text_Load_Name.setText(_translate("LoadInput", "Load Name:"))
        self.Text_Voltage.setText(_translate("LoadInput", "Voltage:"))
        self.Text_Wattage.setText(_translate("LoadInput", "Wattage:"))
        self.Text_Power_Factor.setText(_translate("LoadInput", "Power Factor:"))
        self.Text_VA.setText(_translate("LoadInput", "VA:"))
        self.Text_VA_RESULTS.setText(_translate("LoadInput", "0"))
        self.Text_Utility.setText(_translate("LoadInput", "Utility:"))
        self.Button_Add_To_Window.setText(_translate("LoadInput", "Add To Window"))
        self.Button_Modify_Load.setText(_translate("LoadInput", "Modify Load"))
        self.Button_Remove_Load.setText(_translate("LoadInput", "Remove Load"))
