# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 542)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setEnabled(True)
        self.splitter.setFocusPolicy(QtCore.Qt.NoFocus)
        self.splitter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitter.setLineWidth(1)
        self.splitter.setMidLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(10)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.tabWidge = QtWidgets.QTabWidget(self.splitter)
        self.tabWidge.setObjectName("tabWidge")
        self.tab_Current_Projects = QtWidgets.QWidget()
        self.tab_Current_Projects.setObjectName("tab_Current_Projects")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_Current_Projects)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.list_Current_Projects = QtWidgets.QListWidget(self.tab_Current_Projects)
        self.list_Current_Projects.setObjectName("list_Current_Projects")
        self.gridLayout_3.addWidget(self.list_Current_Projects, 1, 0, 1, 2)
        self.Button_Delete_Project = QtWidgets.QPushButton(self.tab_Current_Projects)
        self.Button_Delete_Project.setObjectName("Button_Delete_Project")
        self.gridLayout_3.addWidget(self.Button_Delete_Project, 0, 1, 1, 1)
        self.Button_Add_Project = QtWidgets.QPushButton(self.tab_Current_Projects)
        self.Button_Add_Project.setObjectName("Button_Add_Project")
        self.gridLayout_3.addWidget(self.Button_Add_Project, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_Mark_As_Finish = QtWidgets.QPushButton(self.tab_Current_Projects)
        self.Button_Mark_As_Finish.setObjectName("Button_Mark_As_Finish")
        self.horizontalLayout.addWidget(self.Button_Mark_As_Finish)
        self.Button_See_More_Details = QtWidgets.QPushButton(self.tab_Current_Projects)
        self.Button_See_More_Details.setObjectName("Button_See_More_Details")
        self.horizontalLayout.addWidget(self.Button_See_More_Details)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.tabWidge.addTab(self.tab_Current_Projects, "")
        self.tab_Past_Due_Projects = QtWidgets.QWidget()
        self.tab_Past_Due_Projects.setObjectName("tab_Past_Due_Projects")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_Past_Due_Projects)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.list_Past_Due_Projects = QtWidgets.QListWidget(self.tab_Past_Due_Projects)
        self.list_Past_Due_Projects.setObjectName("list_Past_Due_Projects")
        self.gridLayout_7.addWidget(self.list_Past_Due_Projects, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Button_Mark_As_Finish_Past_Due = QtWidgets.QPushButton(self.tab_Past_Due_Projects)
        self.Button_Mark_As_Finish_Past_Due.setObjectName("Button_Mark_As_Finish_Past_Due")
        self.horizontalLayout_2.addWidget(self.Button_Mark_As_Finish_Past_Due)
        self.Button_See_More_Details_Past_Due = QtWidgets.QPushButton(self.tab_Past_Due_Projects)
        self.Button_See_More_Details_Past_Due.setObjectName("Button_See_More_Details_Past_Due")
        self.horizontalLayout_2.addWidget(self.Button_See_More_Details_Past_Due)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.tabWidge.addTab(self.tab_Past_Due_Projects, "")
        self.tab_Finished_Projects = QtWidgets.QWidget()
        self.tab_Finished_Projects.setObjectName("tab_Finished_Projects")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_Finished_Projects)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Button_Finished_Projects_Delete = QtWidgets.QPushButton(self.tab_Finished_Projects)
        self.Button_Finished_Projects_Delete.setObjectName("Button_Finished_Projects_Delete")
        self.gridLayout_2.addWidget(self.Button_Finished_Projects_Delete, 0, 1, 1, 1)
        self.list_Finished_Projects = QtWidgets.QListWidget(self.tab_Finished_Projects)
        self.list_Finished_Projects.setObjectName("list_Finished_Projects")
        self.gridLayout_2.addWidget(self.list_Finished_Projects, 1, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Button_Finished_Projects_Mark_as_Current = QtWidgets.QPushButton(self.tab_Finished_Projects)
        self.Button_Finished_Projects_Mark_as_Current.setObjectName("Button_Finished_Projects_Mark_as_Current")
        self.horizontalLayout_3.addWidget(self.Button_Finished_Projects_Mark_as_Current)
        self.Button_Finished_Projects_See_More_Details = QtWidgets.QPushButton(self.tab_Finished_Projects)
        self.Button_Finished_Projects_See_More_Details.setObjectName("Button_Finished_Projects_See_More_Details")
        self.horizontalLayout_3.addWidget(self.Button_Finished_Projects_See_More_Details)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.tabWidge.addTab(self.tab_Finished_Projects, "")
        self.groupBox_More_Details = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_More_Details.setObjectName("groupBox_More_Details")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_More_Details)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_ProjectName = QtWidgets.QLabel(self.groupBox_More_Details)
        self.label_ProjectName.setObjectName("label_ProjectName")
        self.gridLayout_4.addWidget(self.label_ProjectName, 0, 0, 1, 1)
        self.text_ProjectFolder_CHANGE = QtWidgets.QLabel(self.groupBox_More_Details)
        self.text_ProjectFolder_CHANGE.setObjectName("text_ProjectFolder_CHANGE")
        self.gridLayout_4.addWidget(self.text_ProjectFolder_CHANGE, 3, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_More_Details)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_4.addWidget(self.textEdit, 5, 0, 1, 2)
        self.text_ProjectName_CHANGE = QtWidgets.QLabel(self.groupBox_More_Details)
        self.text_ProjectName_CHANGE.setObjectName("text_ProjectName_CHANGE")
        self.gridLayout_4.addWidget(self.text_ProjectName_CHANGE, 0, 1, 1, 1)
        self.Button_Hide_Details = QtWidgets.QPushButton(self.groupBox_More_Details)
        self.Button_Hide_Details.setObjectName("Button_Hide_Details")
        self.gridLayout_4.addWidget(self.Button_Hide_Details, 6, 0, 1, 1)
        self.text_ProjectFolder = QtWidgets.QLabel(self.groupBox_More_Details)
        self.text_ProjectFolder.setObjectName("text_ProjectFolder")
        self.gridLayout_4.addWidget(self.text_ProjectFolder, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_More_Details)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 4, 0, 1, 1)
        self.groupBox_Contacts = QtWidgets.QGroupBox(self.groupBox_More_Details)
        self.groupBox_Contacts.setObjectName("groupBox_Contacts")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_Contacts)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget_Contacts = QtWidgets.QTableWidget(self.groupBox_Contacts)
        self.tableWidget_Contacts.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Contacts.setObjectName("tableWidget_Contacts")
        self.tableWidget_Contacts.setColumnCount(5)
        self.tableWidget_Contacts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Contacts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Contacts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Contacts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Contacts.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Contacts.setHorizontalHeaderItem(4, item)
        self.tableWidget_Contacts.horizontalHeader().setCascadingSectionResizes(True)
        self.gridLayout_5.addWidget(self.tableWidget_Contacts, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_Contacts, 1, 0, 1, 2)
        self.groupBox_dueDates = QtWidgets.QGroupBox(self.groupBox_More_Details)
        self.groupBox_dueDates.setObjectName("groupBox_dueDates")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_dueDates)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableWidget_DueDates = QtWidgets.QTableWidget(self.groupBox_dueDates)
        self.tableWidget_DueDates.setObjectName("tableWidget_DueDates")
        self.tableWidget_DueDates.setColumnCount(2)
        self.tableWidget_DueDates.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_DueDates.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_DueDates.setHorizontalHeaderItem(1, item)
        self.gridLayout_6.addWidget(self.tableWidget_DueDates, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_dueDates, 2, 0, 1, 2)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuResources = QtWidgets.QMenu(self.menubar)
        self.menuResources.setObjectName("menuResources")
        self.menuColorado = QtWidgets.QMenu(self.menuResources)
        self.menuColorado.setObjectName("menuColorado")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_Project_s = QtWidgets.QAction(MainWindow)
        self.actionImport_Project_s.setObjectName("actionImport_Project_s")
        self.actionExport_Projects_s = QtWidgets.QAction(MainWindow)
        self.actionExport_Projects_s.setObjectName("actionExport_Projects_s")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionEdit_Project = QtWidgets.QAction(MainWindow)
        self.actionEdit_Project.setObjectName("actionEdit_Project")
        self.actionMaximize = QtWidgets.QAction(MainWindow)
        self.actionMaximize.setObjectName("actionMaximize")
        self.actionMinimize = QtWidgets.QAction(MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionUtilitys = QtWidgets.QAction(MainWindow)
        self.actionUtilitys.setObjectName("actionUtilitys")
        self.actionReps = QtWidgets.QAction(MainWindow)
        self.actionReps.setObjectName("actionReps")
        self.actionLight_Manufactors = QtWidgets.QAction(MainWindow)
        self.actionLight_Manufactors.setObjectName("actionLight_Manufactors")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionProperties = QtWidgets.QAction(MainWindow)
        self.actionProperties.setObjectName("actionProperties")
        self.menuFile.addAction(self.actionImport_Project_s)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_Projects_s)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionEdit_Project)
        self.menuEdit.addAction(self.actionProperties)
        self.menuView.addAction(self.actionMaximize)
        self.menuView.addAction(self.actionMinimize)
        self.menuColorado.addAction(self.actionUtilitys)
        self.menuColorado.addAction(self.actionReps)
        self.menuColorado.addAction(self.actionLight_Manufactors)
        self.menuResources.addAction(self.menuColorado.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuResources.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidge.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_Delete_Project.setText(_translate("MainWindow", "Delete Project"))
        self.Button_Add_Project.setText(_translate("MainWindow", "Add Project"))
        self.Button_Mark_As_Finish.setText(_translate("MainWindow", "Mark as Finished"))
        self.Button_See_More_Details.setText(_translate("MainWindow", "See More Details"))
        self.tabWidge.setTabText(self.tabWidge.indexOf(self.tab_Current_Projects), _translate("MainWindow", "Current Projects"))
        self.Button_Mark_As_Finish_Past_Due.setText(_translate("MainWindow", "Mark as Finished"))
        self.Button_See_More_Details_Past_Due.setText(_translate("MainWindow", "See More Details"))
        self.tabWidge.setTabText(self.tabWidge.indexOf(self.tab_Past_Due_Projects), _translate("MainWindow", "Past Due Projects"))
        self.Button_Finished_Projects_Delete.setText(_translate("MainWindow", "Delete Project"))
        self.Button_Finished_Projects_Mark_as_Current.setText(_translate("MainWindow", "Mark as Current"))
        self.Button_Finished_Projects_See_More_Details.setText(_translate("MainWindow", "See More Details"))
        self.tabWidge.setTabText(self.tabWidge.indexOf(self.tab_Finished_Projects), _translate("MainWindow", "Finished Projects"))
        self.groupBox_More_Details.setTitle(_translate("MainWindow", "More Details"))
        self.label_ProjectName.setText(_translate("MainWindow", "Project Name:"))
        self.text_ProjectFolder_CHANGE.setText(_translate("MainWindow", "TextLabel"))
        self.text_ProjectName_CHANGE.setText(_translate("MainWindow", "TextLabel"))
        self.Button_Hide_Details.setText(_translate("MainWindow", "Hide Details"))
        self.text_ProjectFolder.setText(_translate("MainWindow", "Project Folder:"))
        self.label_9.setText(_translate("MainWindow", "Adational Notes:"))
        self.groupBox_Contacts.setTitle(_translate("MainWindow", "Contacts"))
        self.tableWidget_Contacts.setSortingEnabled(False)
        item = self.tableWidget_Contacts.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Contact Name"))
        item = self.tableWidget_Contacts.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Contact Phone Number"))
        item = self.tableWidget_Contacts.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidget_Contacts.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Company"))
        item = self.tableWidget_Contacts.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        self.groupBox_dueDates.setTitle(_translate("MainWindow", "Due Dates"))
        item = self.tableWidget_DueDates.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget_DueDates.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Due Date"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuResources.setTitle(_translate("MainWindow", "Resources"))
        self.menuColorado.setTitle(_translate("MainWindow", "Colorado"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionImport_Project_s.setText(_translate("MainWindow", "Import Project(s)"))
        self.actionExport_Projects_s.setText(_translate("MainWindow", "Export Projects(s)"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionEdit_Project.setText(_translate("MainWindow", "Edit Project"))
        self.actionMaximize.setText(_translate("MainWindow", "Maximize"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actionUtilitys.setText(_translate("MainWindow", "Utilitys"))
        self.actionReps.setText(_translate("MainWindow", "Reps"))
        self.actionLight_Manufactors.setText(_translate("MainWindow", "Light Manufactors"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionProperties.setText(_translate("MainWindow", "Properties"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

