# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Voltage_Drop_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VoltageDrop(object):
    def setupUi(self, VoltageDrop):
        VoltageDrop.setObjectName("VoltageDrop")
        VoltageDrop.resize(600, 645)
        self.gridLayout = QtWidgets.QGridLayout(VoltageDrop)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_Inputs = QtWidgets.QGroupBox(VoltageDrop)
        self.groupBox_Inputs.setObjectName("groupBox_Inputs")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_Inputs)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 9, 0, 1, 1)
        self.Button_Show_more_Options = QtWidgets.QPushButton(self.groupBox_Inputs)
        self.Button_Show_more_Options.setObjectName("Button_Show_more_Options")
        self.gridLayout_2.addWidget(self.Button_Show_more_Options, 9, 1, 1, 1)
        self.gridLayout_MainInputs = QtWidgets.QGridLayout()
        self.gridLayout_MainInputs.setObjectName("gridLayout_MainInputs")
        self.text_Circuit_Number = QtWidgets.QLabel(self.groupBox_Inputs)
        self.text_Circuit_Number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_Circuit_Number.setObjectName("text_Circuit_Number")
        self.gridLayout_MainInputs.addWidget(self.text_Circuit_Number, 0, 0, 1, 1)
        self.UserInput_Circuit_Number = QtWidgets.QLineEdit(self.groupBox_Inputs)
        self.UserInput_Circuit_Number.setObjectName("UserInput_Circuit_Number")
        self.gridLayout_MainInputs.addWidget(self.UserInput_Circuit_Number, 0, 1, 1, 1)
        self.text_Wire_Type = QtWidgets.QLabel(self.groupBox_Inputs)
        self.text_Wire_Type.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_Wire_Type.setObjectName("text_Wire_Type")
        self.gridLayout_MainInputs.addWidget(self.text_Wire_Type, 1, 0, 1, 1)
        self.text_Length = QtWidgets.QLabel(self.groupBox_Inputs)
        self.text_Length.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_Length.setObjectName("text_Length")
        self.gridLayout_MainInputs.addWidget(self.text_Length, 0, 2, 1, 1)
        self.text_Load_Type = QtWidgets.QLabel(self.groupBox_Inputs)
        self.text_Load_Type.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_Load_Type.setObjectName("text_Load_Type")
        self.gridLayout_MainInputs.addWidget(self.text_Load_Type, 1, 2, 1, 1)
        self.comboBox_Wire_Type = QtWidgets.QComboBox(self.groupBox_Inputs)
        self.comboBox_Wire_Type.setObjectName("comboBox_Wire_Type")
        self.gridLayout_MainInputs.addWidget(self.comboBox_Wire_Type, 1, 1, 1, 1)
        self.UserInput_Length = QtWidgets.QLineEdit(self.groupBox_Inputs)
        self.UserInput_Length.setObjectName("UserInput_Length")
        self.gridLayout_MainInputs.addWidget(self.UserInput_Length, 0, 3, 1, 1)
        self.comboBox_Load_Type = QtWidgets.QComboBox(self.groupBox_Inputs)
        self.comboBox_Load_Type.setObjectName("comboBox_Load_Type")
        self.gridLayout_MainInputs.addWidget(self.comboBox_Load_Type, 1, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_MainInputs, 5, 1, 1, 1)
        self.gridLayout_MoreOptions = QtWidgets.QGridLayout()
        self.gridLayout_MoreOptions.setObjectName("gridLayout_MoreOptions")
        self.comboBox_Wire_Insulation = QtWidgets.QComboBox(self.groupBox_Inputs)
        self.comboBox_Wire_Insulation.setObjectName("comboBox_Wire_Insulation")
        self.gridLayout_MoreOptions.addWidget(self.comboBox_Wire_Insulation, 0, 4, 1, 1)
        self.text_Phase = QtWidgets.QLabel(self.groupBox_Inputs)
        self.text_Phase.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_Phase.setObjectName("text_Phase")
        self.gridLayout_MoreOptions.addWidget(self.text_Phase, 0, 1, 1, 1)
        self.text_Wire_Insulation = QtWidgets.QLabel(self.groupBox_Inputs)
        self.text_Wire_Insulation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_Wire_Insulation.setObjectName("text_Wire_Insulation")
        self.gridLayout_MoreOptions.addWidget(self.text_Wire_Insulation, 0, 3, 1, 1)
        self.comboBox_Phase = QtWidgets.QComboBox(self.groupBox_Inputs)
        self.comboBox_Phase.setObjectName("comboBox_Phase")
        self.gridLayout_MoreOptions.addWidget(self.comboBox_Phase, 0, 2, 1, 1)
        self.text_Wire_Size = QtWidgets.QLabel(self.groupBox_Inputs)
        self.text_Wire_Size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_Wire_Size.setObjectName("text_Wire_Size")
        self.gridLayout_MoreOptions.addWidget(self.text_Wire_Size, 1, 1, 1, 1)
        self.comboBox_Wire_Size = QtWidgets.QComboBox(self.groupBox_Inputs)
        self.comboBox_Wire_Size.setObjectName("comboBox_Wire_Size")
        self.gridLayout_MoreOptions.addWidget(self.comboBox_Wire_Size, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_MoreOptions, 7, 1, 1, 1)
        self.groupBox_Load_List = QtWidgets.QGroupBox(self.groupBox_Inputs)
        self.groupBox_Load_List.setObjectName("groupBox_Load_List")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_Load_List)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea_Loads = QtWidgets.QScrollArea(self.groupBox_Load_List)
        self.scrollArea_Loads.setWidgetResizable(True)
        self.scrollArea_Loads.setObjectName("scrollArea_Loads")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 141, 73))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_Load_List = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_Load_List.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Load_List.setObjectName("gridLayout_Load_List")
        self.scrollArea_Loads.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea_Loads, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_Load_List, 3, 0, 5, 1)
        self.gridLayout.addWidget(self.groupBox_Inputs, 1, 1, 1, 4)
        self.text_Panel_Name = QtWidgets.QLabel(VoltageDrop)
        self.text_Panel_Name.setObjectName("text_Panel_Name")
        self.gridLayout.addWidget(self.text_Panel_Name, 0, 1, 1, 1)
        self.UserInput_Panel_Name = QtWidgets.QLineEdit(VoltageDrop)
        self.UserInput_Panel_Name.setObjectName("UserInput_Panel_Name")
        self.gridLayout.addWidget(self.UserInput_Panel_Name, 0, 2, 1, 1)
        self.horizontalLayout_Phase = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Phase.setObjectName("horizontalLayout_Phase")
        self.text_Phase_A = QtWidgets.QLabel(VoltageDrop)
        self.text_Phase_A.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_Phase_A.setObjectName("text_Phase_A")
        self.horizontalLayout_Phase.addWidget(self.text_Phase_A)
        self.UserInput_Phase_A = QtWidgets.QLineEdit(VoltageDrop)
        self.UserInput_Phase_A.setObjectName("UserInput_Phase_A")
        self.horizontalLayout_Phase.addWidget(self.UserInput_Phase_A)
        self.text_Phase_B = QtWidgets.QLabel(VoltageDrop)
        self.text_Phase_B.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_Phase_B.setObjectName("text_Phase_B")
        self.horizontalLayout_Phase.addWidget(self.text_Phase_B)
        self.UserInput_Phase_B = QtWidgets.QLineEdit(VoltageDrop)
        self.UserInput_Phase_B.setObjectName("UserInput_Phase_B")
        self.horizontalLayout_Phase.addWidget(self.UserInput_Phase_B)
        self.text_Phase_C = QtWidgets.QLabel(VoltageDrop)
        self.text_Phase_C.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_Phase_C.setObjectName("text_Phase_C")
        self.horizontalLayout_Phase.addWidget(self.text_Phase_C)
        self.UserInput_Phase_C = QtWidgets.QLineEdit(VoltageDrop)
        self.UserInput_Phase_C.setObjectName("UserInput_Phase_C")
        self.horizontalLayout_Phase.addWidget(self.UserInput_Phase_C)
        self.gridLayout.addLayout(self.horizontalLayout_Phase, 4, 2, 1, 2)
        self.text_Panel_Voltage = QtWidgets.QLabel(VoltageDrop)
        self.text_Panel_Voltage.setObjectName("text_Panel_Voltage")
        self.gridLayout.addWidget(self.text_Panel_Voltage, 0, 3, 1, 1)
        self.comboBox_Panel_Voltage = QtWidgets.QComboBox(VoltageDrop)
        self.comboBox_Panel_Voltage.setObjectName("comboBox_Panel_Voltage")
        self.gridLayout.addWidget(self.comboBox_Panel_Voltage, 0, 4, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(VoltageDrop)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        self.gridLayout.addWidget(self.tableWidget, 3, 2, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_Export = QtWidgets.QPushButton(VoltageDrop)
        self.Button_Export.setObjectName("Button_Export")
        self.horizontalLayout.addWidget(self.Button_Export)
        self.Button_Save_Export = QtWidgets.QPushButton(VoltageDrop)
        self.Button_Save_Export.setObjectName("Button_Save_Export")
        self.horizontalLayout.addWidget(self.Button_Save_Export)
        self.Button_Save = QtWidgets.QPushButton(VoltageDrop)
        self.Button_Save.setObjectName("Button_Save")
        self.horizontalLayout.addWidget(self.Button_Save)
        self.Button_Update_Panel = QtWidgets.QPushButton(VoltageDrop)
        self.Button_Update_Panel.setObjectName("Button_Update_Panel")
        self.horizontalLayout.addWidget(self.Button_Update_Panel)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 2, 1, 2)
        self.groupBox_Results = QtWidgets.QGroupBox(VoltageDrop)
        self.groupBox_Results.setObjectName("groupBox_Results")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_Results)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.text_Total_VA = QtWidgets.QLabel(self.groupBox_Results)
        self.text_Total_VA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_Total_VA.setObjectName("text_Total_VA")
        self.gridLayout_5.addWidget(self.text_Total_VA, 1, 1, 1, 1)
        self.text_Total_Voltage_Drop = QtWidgets.QLabel(self.groupBox_Results)
        self.text_Total_Voltage_Drop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_Total_Voltage_Drop.setObjectName("text_Total_Voltage_Drop")
        self.gridLayout_5.addWidget(self.text_Total_Voltage_Drop, 3, 1, 1, 1)
        self.text_Pre_Voltage_Drop = QtWidgets.QLabel(self.groupBox_Results)
        self.text_Pre_Voltage_Drop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_Pre_Voltage_Drop.setObjectName("text_Pre_Voltage_Drop")
        self.gridLayout_5.addWidget(self.text_Pre_Voltage_Drop, 4, 1, 1, 1)
        self.text_Total_Current = QtWidgets.QLabel(self.groupBox_Results)
        self.text_Total_Current.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_Total_Current.setObjectName("text_Total_Current")
        self.gridLayout_5.addWidget(self.text_Total_Current, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 4, 1, 1)
        self.text_Total_Voltage_Drop_RESULTS = QtWidgets.QLabel(self.groupBox_Results)
        self.text_Total_Voltage_Drop_RESULTS.setObjectName("text_Total_Voltage_Drop_RESULTS")
        self.gridLayout_5.addWidget(self.text_Total_Voltage_Drop_RESULTS, 3, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 0, 1, 1)
        self.text_Pre_Voltage_Drop_2 = QtWidgets.QLabel(self.groupBox_Results)
        self.text_Pre_Voltage_Drop_2.setObjectName("text_Pre_Voltage_Drop_2")
        self.gridLayout_5.addWidget(self.text_Pre_Voltage_Drop_2, 4, 2, 1, 1)
        self.text_A = QtWidgets.QLabel(self.groupBox_Results)
        self.text_A.setObjectName("text_A")
        self.gridLayout_5.addWidget(self.text_A, 2, 3, 1, 1)
        self.text_Wire_size = QtWidgets.QLabel(self.groupBox_Results)
        self.text_Wire_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_Wire_size.setObjectName("text_Wire_size")
        self.gridLayout_5.addWidget(self.text_Wire_size, 5, 1, 1, 1)
        self.text_pre = QtWidgets.QLabel(self.groupBox_Results)
        self.text_pre.setObjectName("text_pre")
        self.gridLayout_5.addWidget(self.text_pre, 4, 3, 1, 1)
        self.Text_Wire_Size_RESULTS = QtWidgets.QLabel(self.groupBox_Results)
        self.Text_Wire_Size_RESULTS.setObjectName("Text_Wire_Size_RESULTS")
        self.gridLayout_5.addWidget(self.Text_Wire_Size_RESULTS, 5, 2, 1, 1)
        self.text_Wire_SIze_Label = QtWidgets.QLabel(self.groupBox_Results)
        self.text_Wire_SIze_Label.setObjectName("text_Wire_SIze_Label")
        self.gridLayout_5.addWidget(self.text_Wire_SIze_Label, 5, 3, 1, 1)
        self.text_Total_Current_RESULTS = QtWidgets.QLabel(self.groupBox_Results)
        self.text_Total_Current_RESULTS.setObjectName("text_Total_Current_RESULTS")
        self.gridLayout_5.addWidget(self.text_Total_Current_RESULTS, 2, 2, 1, 1)
        self.text_Circuit_Voltage_RESULTS = QtWidgets.QLabel(self.groupBox_Results)
        self.text_Circuit_Voltage_RESULTS.setObjectName("text_Circuit_Voltage_RESULTS")
        self.gridLayout_5.addWidget(self.text_Circuit_Voltage_RESULTS, 0, 2, 1, 1)
        self.text_Total_VA_RESULTS = QtWidgets.QLabel(self.groupBox_Results)
        self.text_Total_VA_RESULTS.setObjectName("text_Total_VA_RESULTS")
        self.gridLayout_5.addWidget(self.text_Total_VA_RESULTS, 1, 2, 1, 1)
        self.text_Circuit_Voltage = QtWidgets.QLabel(self.groupBox_Results)
        self.text_Circuit_Voltage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_Circuit_Voltage.setObjectName("text_Circuit_Voltage")
        self.gridLayout_5.addWidget(self.text_Circuit_Voltage, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Button_Update_Circuit = QtWidgets.QPushButton(self.groupBox_Results)
        self.Button_Update_Circuit.setObjectName("Button_Update_Circuit")
        self.horizontalLayout_2.addWidget(self.Button_Update_Circuit)
        self.Button_Cancel = QtWidgets.QPushButton(self.groupBox_Results)
        self.Button_Cancel.setObjectName("Button_Cancel")
        self.horizontalLayout_2.addWidget(self.Button_Cancel)
        self.Button_Add_To_Table = QtWidgets.QPushButton(self.groupBox_Results)
        self.Button_Add_To_Table.setObjectName("Button_Add_To_Table")
        self.horizontalLayout_2.addWidget(self.Button_Add_To_Table)
        self.Button_Remove_Circuit = QtWidgets.QPushButton(self.groupBox_Results)
        self.Button_Remove_Circuit.setObjectName("Button_Remove_Circuit")
        self.horizontalLayout_2.addWidget(self.Button_Remove_Circuit)
        self.Button_Reset = QtWidgets.QPushButton(self.groupBox_Results)
        self.Button_Reset.setObjectName("Button_Reset")
        self.horizontalLayout_2.addWidget(self.Button_Reset)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 7, 0, 1, 5)
        self.gridLayout.addWidget(self.groupBox_Results, 2, 2, 1, 2)

        self.retranslateUi(VoltageDrop)
        QtCore.QMetaObject.connectSlotsByName(VoltageDrop)

    def retranslateUi(self, VoltageDrop):
        _translate = QtCore.QCoreApplication.translate
        VoltageDrop.setWindowTitle(_translate("VoltageDrop", "Voltage Drop Calculator"))
        self.groupBox_Inputs.setTitle(_translate("VoltageDrop", "Inputs"))
        self.Button_Show_more_Options.setText(_translate("VoltageDrop", "Show more Options"))
        self.text_Circuit_Number.setText(_translate("VoltageDrop", "Circuit #:"))
        self.text_Wire_Type.setText(_translate("VoltageDrop", "Wire Type:"))
        self.text_Length.setText(_translate("VoltageDrop", "Length(ft):"))
        self.text_Load_Type.setText(_translate("VoltageDrop", "Load Type:"))
        self.text_Phase.setText(_translate("VoltageDrop", "Phase:"))
        self.text_Wire_Insulation.setText(_translate("VoltageDrop", "Wire Insulation:"))
        self.text_Wire_Size.setText(_translate("VoltageDrop", "Wire Size:"))
        self.groupBox_Load_List.setTitle(_translate("VoltageDrop", "Luminare/Load List"))
        self.text_Panel_Name.setText(_translate("VoltageDrop", "Panel Name:"))
        self.text_Phase_A.setText(_translate("VoltageDrop", "Phase A:"))
        self.text_Phase_B.setText(_translate("VoltageDrop", "Phase :B"))
        self.text_Phase_C.setText(_translate("VoltageDrop", "Phase C:"))
        self.text_Panel_Voltage.setText(_translate("VoltageDrop", "Panel Voltage and phase"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("VoltageDrop", "Circuit Number"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("VoltageDrop", "Length"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("VoltageDrop", "Total VA"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("VoltageDrop", "Circuit Voltage"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("VoltageDrop", "Current"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("VoltageDrop", "Wire Size"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("VoltageDrop", "Wire Type"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("VoltageDrop", "Wire Insulation"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("VoltageDrop", "Phase"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("VoltageDrop", "Total Voltage Drop"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("VoltageDrop", "% Voltage Drop"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("VoltageDrop", "Load Type"))
        self.Button_Export.setText(_translate("VoltageDrop", "Export to Excel"))
        self.Button_Save_Export.setText(_translate("VoltageDrop", "Save and Export to Excel"))
        self.Button_Save.setText(_translate("VoltageDrop", "Save"))
        self.Button_Update_Panel.setText(_translate("VoltageDrop", "Update Panel"))
        self.groupBox_Results.setTitle(_translate("VoltageDrop", "Results"))
        self.text_Total_VA.setText(_translate("VoltageDrop", "Total VA:"))
        self.text_Total_Voltage_Drop.setText(_translate("VoltageDrop", "Total Voltage Drop:"))
        self.text_Pre_Voltage_Drop.setText(_translate("VoltageDrop", "% of Voltage Drop:"))
        self.text_Total_Current.setText(_translate("VoltageDrop", "Total Current:"))
        self.text_Total_Voltage_Drop_RESULTS.setText(_translate("VoltageDrop", "0"))
        self.text_Pre_Voltage_Drop_2.setText(_translate("VoltageDrop", "0"))
        self.text_A.setText(_translate("VoltageDrop", "A"))
        self.text_Wire_size.setText(_translate("VoltageDrop", "Wire Size:"))
        self.text_pre.setText(_translate("VoltageDrop", "%"))
        self.Text_Wire_Size_RESULTS.setText(_translate("VoltageDrop", "12"))
        self.text_Wire_SIze_Label.setText(_translate("VoltageDrop", "AWG"))
        self.text_Total_Current_RESULTS.setText(_translate("VoltageDrop", "0"))
        self.text_Circuit_Voltage_RESULTS.setText(_translate("VoltageDrop", "0"))
        self.text_Total_VA_RESULTS.setText(_translate("VoltageDrop", "0"))
        self.text_Circuit_Voltage.setText(_translate("VoltageDrop", "Circuit Voltage:"))
        self.Button_Update_Circuit.setText(_translate("VoltageDrop", "Update Circuit"))
        self.Button_Cancel.setText(_translate("VoltageDrop", "Cancel"))
        self.Button_Add_To_Table.setText(_translate("VoltageDrop", "Add to Panel"))
        self.Button_Remove_Circuit.setText(_translate("VoltageDrop", "Remove Circuit"))
        self.Button_Reset.setText(_translate("VoltageDrop", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VoltageDrop = QtWidgets.QWidget()
    ui = Ui_VoltageDrop()
    ui.setupUi(VoltageDrop)
    VoltageDrop.show()
    sys.exit(app.exec_())

